<main class="form-page">
    <div class="form-container panel">
        <h2 class="form-title"><?= !empty($director) ? 'Editar Director' : 'Agregar Director' ?></h2>
        <p class="form-subtitle">
            <?= !empty($director)
                ? 'Modifique los datos del director seleccionado.'
                : 'Complete los datos para registrar un nuevo director en el sistema.' ?>
        </p>
        <form method='post' action="<?= !empty($director) ? BASE_URL . 'updateDirector/' . $director->id : BASE_URL . 'addDirector' ?>">
            <div class='form-group'>
                <label for='nombre'>Nombre</label>
                <input type='text' id='nombre' name='nombre' value="<?= !empty($director) ? $director->nombre : '' ?>" required>
            </div>
            <div class='form-group'>
                <label for='nacionalidad'>Nacionalidad</label>
                <input type='text' id='nacionalidad' name='nacionalidad' value="<?= !empty($director) ? $director->nacionalidad : '' ?>" required>
            </div>

            <button type="submit" class="btn btn-primary btn-large "><?= !empty($director) ? 'Actualizar Director' : 'Agregar Director' ?></button>
        </form>
    </div>
</main>