<div class="container-login">
<h2><?= !empty($pelicula) ? 'Editar Película' : 'Agregar Película' ?></h2>

<form method='post' action="<?= $pelicula ? BASE_URL.'editarPelicula/'.$pelicula->id : BASE_URL.'addPelicula' ?>">
    <div class='form-group'>
        <label for='email'>Titulo</label>
        <input type='text' id='titulo' name='titulo' value="<?= !empty($pelicula) ? $pelicula->titulo : '' ?>" required>
    </div>
    <div class='form-group'>
        <label for='anio'>Año</label>
        <input type='number' id='anio' name='anio'  value="<?= !empty($pelicula) ? $pelicula->anio : '' ?>" required>
    </div>
    <div class='form-group'>
        <label for='anio'>Duracion</label>
        <input type='number' id='duracion' name='duracion'  value="<?= !empty($pelicula) ? $pelicula->duracion : '' ?>" required>
    </div>
    <input type="hidden" name="director" value="1">
   
    <button type="submit"class="btn-login"><?= !empty($pelicula) ? 'Actualizar Película' : 'Agregar Película' ?></button>
   
</form>
</div>